### ISSUE TITLE
Message field still default Green / White

### ISSUE THREAD

**Issue by purplpasta** [m4heshd/whatsapp-desktop-dark#62] opened 2019-10-05 18:46 UTC
Everything worked just fine until like one day ago. 
WhatsApp switched to light theme on its own, so I reinstalled the dark theme. However now the message fields are default colors (white / green) and not grey. This wouldn't be so bad, but it makes the text hard to read that is still grey. 
Maybe it has something to do with the newest version, because it doesn't start up properly after launching WADark.exe. 
![grafik](https://user-images.githubusercontent.com/56203839/66259423-22c3dd80-e7b1-11e9-9ec9-597e55ab9712.png)

**Comment by m4heshd** [comment] 2019-10-06 08:07
Hi @OwO-tism, This is because you're using an older version of WADark. Please download the latest version and reinstall. Closing this since it's a duplicate of issue #47. You can comment there if you still have an issue.

**Closed as completed** 2019-10-06 12:24 UTC
Labels: Duplicate, Not-an-issue 🚫
