### ISSUE TITLE
Could not build the source on my system.

### ISSUE THREAD

**Issue by mrillusi0n** [m4heshd/whatsapp-desktop-dark#31] opened 2019-09-23 02:01 UTC
> resourcehacker@4.2.51 postinstall /Volumes/misc/whatsapp-desktop-dark/node_modules/resourcehacker
> node scripts/install.js

Downloading ResourceHacker by Angus Johnson...
_http_client.js:107
  var expectedProtocol = defaultAgent.protocol;
                                      ^

TypeError: Cannot read property 'protocol' of undefined
    at new ClientRequest (_http_client.js:107:39)
    at request (http.js:42:10)
    at Object.get (http.js:46:13)
    at Object.<anonymous> (/Volumes/misc/whatsapp-desktop-dark/node_modules/resourcehacker/scripts/install.js:23:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! resourcehacker@4.2.51 postinstall: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the resourcehacker@4.2.51 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Kadantte** [comment] 2019-09-23 06:12
I build the tool with Github workflows so here's what happens:
The build on node 8.x was successful but in node version 10.x and 12.x it fails I dunno why but  I think there's a problem with resourcehacker.

![image](https://user-images.githubusercontent.com/11579313/65404691-7a397500-ddd1-11e9-8361-c4a52d5a4377.png)

**Comment by m4heshd** [comment] 2019-09-23 10:12
This is a duplicate of #11 and #25. This isn't an issue for mac users. You can simply ignore the error thrown by `resourcehacker` because It's a module specific for the Windows build.

**Closed as completed by m4heshd** 2019-09-23 10:12 UTC
Labels: Duplicate, Not-an-issue 🚫
