### ISSUE TITLE
v0.4.930 contrast/color issues

### ISSUE THREAD

**Issue by Ktklein72** [m4heshd/whatsapp-desktop-dark#154] opened 2020-02-28 20:08 UTC
This is for Windows version btw...

I just updated and here are 2 issues I'm seeing:
Quoted/replied text is light text on white background and the dialog box where you type has dark grey text making it hard to see what you're typing.  The latter issue I think was previously reported...

![image](https://user-images.githubusercontent.com/5505779/75583642-05cbc780-5a3c-11ea-9bfe-e8b75f78f1c2.png)

**Comment by m4heshd** [comment] 2020-02-29 00:28
This is a duplicate of #139 and all of those issues are fixed in the latest release.

**Closed as completed by m4heshd** 2020-02-29 00:28 UTC
Labels: Duplicate

**Comment by Ktklein72** [comment] 2020-02-29 00:31
Hi.  Before I opened issue# 154, I did a fresh download and installation 
of v0.4.930 and those are the issues I experienced.  If they're fixed, 
am I doing something incorrect?  How can I go about resolving those 
issues if I am on the latest build?

Thanks in advance for your help!

Regards,
Kevin

------ Original Message ------

**Comment by m4heshd** [comment] 2020-02-29 00:39
You must've accidentally downloaded the previous version of WADark. Please go ahead and download from the following URL. 
https://github.com/m4heshd/whatsapp-desktop-dark/releases/tag/0.4.930

**Comment by Ktklein72** [comment] 2020-02-29 00:48
re-did the d/l and installation and all is good now.  Thank you!
