### ISSUE TITLE
Is this on purpose?

### ISSUE THREAD

**Issue by NicolasPL64** [m4heshd/whatsapp-desktop-dark#42] opened 2019-09-26 22:11 UTC
![image](https://user-images.githubusercontent.com/31411531/65728436-97e03600-e080-11e9-86c7-c414f05b1c0e.png)

The white borders

**Comment by m4heshd** [comment] 2019-09-26 22:14
Hi @NicolasPL64,
This is a duplicate of issue #6 and you can get updated on there. Also it's currently being discussed on https://t.me/wadarkmodechat

**Closed as completed by m4heshd** 2019-09-26 22:14 UTC
Labels: Duplicate
