### ISSUE TITLE
Text on dark background should be white

### ISSUE THREAD

**Issue by 0ffTopic** [m4heshd/whatsapp-desktop-dark#151] opened 2020-02-27 11:42 UTC
When typing in a dark theme, text stays gray and not white, makes it harder to read.
![image](https://user-images.githubusercontent.com/9589169/75441788-2d486480-5956-11ea-9f41-0848fd122748.png)

**Comment by raphaelluethy** [comment] 2020-02-27 13:08
I wrote a small edit note in #152 
but as i mentioned above, add 
```css
._3u328 {
    color: var(--lighter) !important;
}
```
to styles/dark.css

**Comment by 0ffTopic** [comment] 2020-02-27 14:22
Thanks for that, but I have a question: 
does it work for all the themes available or just for default?
I had Android Dark selected and reapplied after the change you mentioned and it stayed the same, tried the default theme and still have the same issue, I'm on Windows

**Comment by raphaelluethy** [comment] 2020-02-27 16:36
> Thanks for that, but I have a question:
> does it work for all the themes available or just for default?
> I had Android Dark selected and reapplied after the change you mentioned and it stayed the same, tried the default theme and still have the same issue, I'm on Windows

i‘d say it should still work, since only 1 css file gets injected, and i used the var() function for the colors :)

**Comment by m4heshd** [comment] 2020-02-27 22:08
This is a duplicate of #139 and fixed in the latest release. Closing.

**Closed as completed by m4heshd** 2020-02-27 22:08 UTC
Labels: Duplicate
