### ISSUE TITLE
Messages no longer showing as read by contact

### ISSUE THREAD

**Issue by thetrev** [m4heshd/whatsapp-desktop-dark#150] opened 2020-02-27 10:51 UTC
I think there has been an update in the past 24 hours, but both the telegram and whatsapp dark themes are causing the messages to show as delivered, but not read by the receiving contacts. I have reinstalled the themes and started clean, they are working without any theme applied so I'm guessing it's an overnight update that's thrown it out of whack?

**Comment by m4heshd** [comment] 2020-02-27 10:53
This issue is a duplicate of #139 and already fixed in the local repo. Please wait for the next release.

**Closed as completed by m4heshd** 2020-02-27 10:53 UTC
Labels: Duplicate
