### ISSUE TITLE
Emojis with a white background

### ISSUE THREAD

**Issue by juanra** [m4heshd/whatsapp-desktop-dark#6] opened 2019-09-03 15:02 UTC
The emojis have a white background after applying the script. Do you know if there is a way to fix this?

<img width="185" alt="Screen Shot 2019-09-03 at 9 59 49 AM" src="https://user-images.githubusercontent.com/112196/64184922-d859e480-ce31-11e9-870f-72767fbeb491.png">

**Comment by timea-techgirl** [comment] 2019-09-03 15:12
@juanra The emoji itself is a picture with white background, can't change it.

**Comment by m4heshd** [comment] 2019-09-03 15:13
Hi @juanra,

This issue has been raised multiple times on XDA and Reddit. Unfortunately emojis on the emoji tab are loaded to a canvas from one big WEBP with a white background. Actually multiple WEBP files according to the emoji category. So it's not fixable at all. I've tried. Really sorry about that.

![image](https://user-images.githubusercontent.com/6711514/64185803-62826700-ce8b-11e9-85b9-5be317e345a8.png)

Maybe somebody can recreate the WEBP file with a darker background so i can replace them via the script in the installation process.

**Comment by Slyther** [comment] 2019-09-08 05:05
Hi,

So this got me curious and I started checking out the image assets on whatsapp, but I see like 4 or 5 different versions of each emoji group, in jpeg, webp, png, with backgrounds, without backgrounds, and even with slightly different emojis. 

![wa_icons](https://user-images.githubusercontent.com/4093602/64483666-ac3cbb80-d1c3-11e9-8de0-b5fcae8c82cc.png)


If I'm in the right place, then here's a couple of questions:

1. How do you know which ones are used in the emoji tab?
2. Wouldn't you be able to just grab the already existing versions without backgrounds and rename them to match the ones currently being used?

**Comment by m4heshd** [comment] 2019-09-08 08:38
Hi @Slyther, 

It's great that you're looking into this. What you're looking for is all the emoji WEBP files with a white background.

**Comment by juanra** [comment] 2019-09-09 18:55
Thanks @timeakesmarky and @m4heshd for the context.  I'm going to look for the WEBP file I will try to recreate it with the black background. I let you know my progress.

Do you know what path this file is in?

**Comment by m4heshd** [comment] 2019-09-09 21:47
That's great to hear. Make sure the background color is `#272c35` so the emojis will blend in with the app background. Let us know your progress.

**Comment by juanra** [comment] 2019-09-19 15:49
> Thanks @timeakesmarky and @m4heshd for the context. I'm going to look for the WEBP file I will try to recreate it with the black background. I let you know my progress.
> 
> Do you know what path this file is in?

Hi guys, do you know in which path I can find the emoji resources?

**Comment by mrillusi0n** [comment] 2019-09-24 04:30
> That's great to hear. Make sure the background color is `#272c35` so the emojis will blend in with the app background. Let us know your progress.

I can try recreating with the specced bg color, but I was not able to find the original webp files. Could you please tell me where I can find them?

**Comment by Slyther** [comment] 2019-09-24 06:29
@juanra @mrillusi0n you guys need to extract the files from the *.asar file for  whatsapp. I guess the easiest way to get to that is by using the asar file from the backup folder. You need the asar node module to extract the assets off of the file. Syntax is as follows:

`asar extract app.asar destinationfolder`

The webp files are in the img folder. A search of *.webp will give you the files. Don't mind the ones without background as those are different sizes. I kinda gave up on this as I'm not sure how to modify webp files. The photoshop extensions I've tried have only corrupted the files, and there's like 400 files to modify, so a programmatic approach is basically necessary. The background eraser algorithm probably exists as an open source algorithm somewhere, so realistically, it *should* be possible... I'm just not sure where to start looking.

**Comment by mrillusi0n** [comment] 2019-09-24 06:53
Thanks @Slyther. I think I can try doing it by Ps's Batch-Processing. I think it's better to make them transparent, rather than having `#272c35` hardcoded, as @m4heshd said.

**Comment by m4heshd** [comment] 2019-09-24 14:26
I have no idea why WhatsApp's doing this. If you take a look there are identical WEBP files with transparency for ones with a white background slightly differs in size and quality. Like 1 - 3 KB differences.

![image](https://user-images.githubusercontent.com/6711514/65520519-524b2e00-df05-11e9-8145-c0c688a06b48.png)


 I'm all for improving render time, performance..etc. but that's just a huge waste of resources in my opinion.

@mrillusi0n, i suggested adding a bg because adding an alpha channel might change the behaviors a bit. But I would also like them to have a transparent background because any future modification to the color palette would be much simpler then.

**Comment by mrillusi0n** [comment] 2019-09-24 14:36
@m4heshd Yeah, I did come across that. Right now, I've just filtered out the webp files. And nothing more. Is there a way you can load them from the png's? Because they are already transparent. I don't know, that might be a dumb suggestion.

**Comment by m4heshd** [comment] 2019-09-24 16:30
PNGs can work but unfortunately styling for that particular part is dynamically generated via JS on runtime. So not possible to override that. It has to be the images.

**Comment by mrillusi0n** [comment] 2019-09-24 16:36
@m4heshd Do you have any other platform for discussions? A Telegram Channel would be great.

**Comment by m4heshd** [comment] 2019-09-24 17:22
Sure. Here's the one i just created. 
https://t.me/wadarkmode
I'll add it to documentation later.

**Comment by mrillusi0n** [comment] 2019-09-24 17:41
> Sure. Here's the one i just created.
> https://t.me/wadarkmode
> I'll add it to documentation later.

You need to share us a group link where we can converse too. Only you can broadcast messages on there.

Edit: Sorry, it should have been a Public Group instead of a Telegram Channel, for discussions.

**Comment by m4heshd** [comment] 2019-09-24 18:18
My bad. Not a Telegram user. 😁
Here's the link - https://t.me/wadarkmodechat

**Comment by m4heshd** [comment] 2019-09-25 03:07
There's some progress but nowhere even near achieving the actual goal.

![image](https://user-images.githubusercontent.com/6711514/65566193-bb678b80-df6f-11e9-8504-529d29bda7af.png)

This is pretty much an impossible task but we don't have to lose hope.

**Comment by Slyther** [comment] 2019-09-25 12:21
@m4heshd was this done purely with Photoshop batch? If we could find a way to do the  image modification programmatically, this could be easily doable.

[This](https://github.com/Intervox/node-webp) can turn webp images into streams and buffers, we'd just need an image manipulation library, even a rudimentary one could realistically work. I'll start looking around.

**Comment by m4heshd** [comment] 2019-09-25 12:34
@Slyther It's really good to hear that you're putting real effort into this. I did this on the source code level without dealing with images since it literally gave me migraines looking through thousands of white background images. 

Still trying to do this on source level because there seems to be 100s of MBs worth images that we'll need to replace for it to work as intended. That's definitely going on the cons list if we do that. This shouldn't be this much of a struggle in my honest opinion. But since we have no choice, we'll work with the hand that has been dealt to us.

**Comment by NicolasPL64** [comment] 2019-09-26 22:18
@m4heshd Man, you are the best!!

**Comment by m4heshd** [comment] 2019-09-26 22:29
@NicolasPL64 I hardly believe that but thank you for the kind compliment. 😊

**Comment by m4heshd** [comment] 2019-10-02 04:30
Issue is finally fixed on 73c4bdc0108362b8d81e5dbf11e021df6e84d736. **A big round of applause goes to @Slyther for his immense effort and bringing this to life** 👏. Anyone can find his script which made this possible [right here](https://www.npmjs.com/package/transparent-whatsapp-spritesheets).

Also thanks to everyone who's been testing the changes on our Telegram group including @mrillusi0n. I'm keeping this discussion open for the moment in case of any further improvements and updates. Congrats everyone. This was a difficult one.. 🤘

**Comment by KeronCyst** [comment] 2019-10-07 18:56
👏 This issue can finally be closed a month later, lol!

**Closed as completed** 2020-02-01 11:32 UTC
Labels: Known-issue, Fixed 🎉, Discussion 💬
