### ISSUE TITLE
Not working in last Whatsapp Desktop version

### ISSUE THREAD

**Issue by mortenanakin** [m4heshd/whatsapp-desktop-dark#117] opened 2020-01-22 23:05 UTC

**Comment by ghost** [comment] 2020-01-23 12:38
Duplicate of #114

**Comment by nzec** [comment] 2020-01-26 13:23
Doesn't seem to be working at all for me. The script is just stuck at Killling Whatsapp part for over an hour.

**Comment by nathantaal** [comment] 2020-01-28 10:10
> Doesn't seem to be working at all for me. The script is just stuck at Killling Whatsapp part for over an hour.

I've had that problem, you should retry it a few times

**Comment by OBadstue** [comment] 2020-01-30 12:21
I have the same problem, have retried over a dozen times, even tried reinstalling whatsapp. Still either stuck at 'killing whatsapp' forever, or just crashes at the same stage

**Comment by ghost** [comment] 2020-01-30 12:49
@OBadstue try to execute the WADark.exe as admin or kill the whatsapp.exe process with task management.

**Comment by m4heshd** [comment] 2020-02-01 11:26
Closing this since the issue is a duplicate of #113 and has been fixed in the latest release.

**Closed as completed by m4heshd** 2020-02-01 11:26 UTC
Labels: Duplicate
