### ISSUE TITLE
Black theme update doesn't change convo bubble background, hard to read. 

### ISSUE THREAD

**Issue by wvalko** [m4heshd/whatsapp-desktop-dark#74] opened 2019-10-14 02:24 UTC
![image](https://user-images.githubusercontent.com/29451850/66726582-d3f4f400-edff-11e9-9cc1-f496b3361a38.png)

Ran normal installer, have to squint to read.  Help :)

**Comment by tslin89** [comment] 2019-10-14 09:25
Same here. The rest looks awesome but can't read messages.
![2019-10-14_17-05-19](https://user-images.githubusercontent.com/5475019/66741219-93e94c00-eea7-11e9-91f0-677b2244c13a.png)

**Comment by omar-shukurov** [comment] 2019-10-14 16:51
i really liked the app, But PLease fix this issue- Waiting excitingly

**Comment by m4heshd** [comment] 2019-10-14 17:23
Hi, Please check your dark mode version because this issue was fixed in WADark [v3.0.4941](https://github.com/m4heshd/whatsapp-desktop-dark/releases/tag/0.3.4941). If so, this would be a duplicate of issue #47.

**Comment by tslin89** [comment] 2019-10-15 02:13
Hi, I am using Dark Mode Version 0.3.4941. 

I am on Windows 10 Pro 64 bit with Dark Mode (if this is related)

![2019-10-15_10-11-26](https://user-images.githubusercontent.com/5475019/66794493-4a930e00-ef34-11e9-8bb4-972a60edf5fe.png)

**Comment by m4heshd** [comment] 2019-10-15 17:32
Hi @tslin306, this is really odd because nobody else is having this issue with the versions you're on. Can you try a fresh installation of WhatsApp desktop?

**Comment by wvalko** [comment] 2019-10-15 17:37
I will confirm for myself, I had an older version installed.  Once updated to latest version all looks great!

**Comment by exadeci** [comment] 2019-10-16 00:50
@m4heshd I had the same issue because it offered me to restore a backup and when I did it would appear the same.

By refusing to use the backup it applied it properly.

**Comment by tslin89** [comment] 2019-10-16 06:45
> Hi @tslin306, this is really odd because nobody else is having this issue with the versions you're on. Can you try a fresh installation of WhatsApp desktop?

It is working fine after uninstalling and reinstalling WhatsApp and applying dark theme again. Thanks a lot. I really love the color.

**Comment by Ktklein72** [comment] 2019-10-16 13:21
I'm not having the issue the OP stated but it is similar - not sure what to call it.  I'll try and post a screen shot or two.  On only the posts I make, instead of a conversation bubble it covers the wallpaper from end-to-end, the entire width.  On post from others all is normal.
![Capture1](https://user-images.githubusercontent.com/5505779/66923160-4f1ffb00-eff6-11e9-9770-e2063ad4ad4e.PNG)
![Capture2](https://user-images.githubusercontent.com/5505779/66923161-4f1ffb00-eff6-11e9-82d0-7ccc92d9b1ec.PNG)

**Comment by m4heshd** [comment] 2019-10-16 14:22
@Ktklein72, This issue is already being tracked in #68. Closing this since the issue has been solved.

**Closed as completed by m4heshd** 2019-10-16 14:22 UTC
Labels: Duplicate
