### ISSUE TITLE
Keyboard highlight context menu BG color white

### ISSUE THREAD

**Issue by KeronCyst** [m4heshd/whatsapp-desktop-dark#1] opened 2019-08-23 15:49 UTC
1. Click the context menu arrow in the upper-right corner of any message
2. Press the Up/Down arrow keys
3. Background is a sharp white instead of the nicer `onmouseover` gray

![image](https://user-images.githubusercontent.com/13827055/63605468-dc108000-c582-11e9-8623-877592a9803c.png)

**Comment by m4heshd** [comment] 2019-08-23 15:52
That's weird. It's fine for me on both platforms. Which platform are you on?

![image](https://user-images.githubusercontent.com/6711514/63605896-807adc80-c5ec-11e9-8cb3-ddb26cd0533b.png)

![image](https://user-images.githubusercontent.com/6711514/63606353-7efde400-c5ed-11e9-8e4c-b6f97a2b0ccc.png)

**Comment by KeronCyst** [comment] 2019-08-23 16:05
It only happens using keyboard arrows, not mousing over (which fixes it immediately, and arrows cause more contrast again right afterwards). I'm using WhatsApp Desktop Version 0.3.4375 on Win10 Home.

**Comment by m4heshd** [comment] 2019-08-23 16:39
Ok. I can reproduce the issue when using arrow keys. It'll be fixed soon. Thanks for reporting.

**Comment by m4heshd** [comment] 2019-09-03 23:40
Closing this issue since It's been fixed on 3cdb607b9f27a9746ba6e2827e136aae132ff41a. Enjoy..

**Closed as completed by m4heshd** 2019-09-03 23:40 UTC
Labels: Bug 🐞, Fixed 🎉
