### ISSUE TITLE
Theme resets on every restart - MacOS Catalina Issue

### ISSUE THREAD

**Issue by TheMorgz** [m4heshd/whatsapp-desktop-dark#80] opened 2019-10-21 12:23 UTC
I install the theme. Restart my Mac, and the theme settings do not persist after the reboot of the machine. If I try to re-install the theme after it resets, then it messes the theme up(Grey patches around the message blocks) with inconsistent styling.

**Comment by HillTravis** [comment] 2019-10-21 16:00
Related to #77

**Comment by m4heshd** [comment] 2020-01-31 22:24
Closing this since it's a duplicate of #77 and has been fixed in the latest release.

**Closed as completed by m4heshd** 2020-01-31 22:24 UTC
Labels: Duplicate
