### ISSUE TITLE
script doesn't with with arabic username of pc

### ISSUE THREAD

**Issue by ARDVDZ** [m4heshd/whatsapp-desktop-dark#212] opened 2020-04-30 07:29 UTC
th script doesn't with with arabic username of pc

**Comment by chrmey** [comment] 2020-04-30 20:00
At this point i would normally ask you to explain in more detail, but i dont even understand what you are trying to tell. So my question at this point is:
WHAT?

**Comment by m4heshd** [comment] 2020-04-30 20:04
Duplicate of #29. Please check the workarounds there.

**Closed as completed by m4heshd** 2020-04-30 20:04 UTC
Labels: Duplicate
