### ISSUE TITLE
Random white thing

### ISSUE THREAD

**Issue by NicolasPL64** [m4heshd/whatsapp-desktop-dark#134] opened 2020-02-05 21:17 UTC
![image](https://user-images.githubusercontent.com/31411531/73883980-ed98cc00-4832-11ea-95d8-b3c282ded814.png)

I don't know why did this happen

**Comment by m4heshd** [comment] 2020-02-05 21:30
That's weird. ~~Definitely something on WhatsApp's side because from the looks of it, It's an empty message~~. Let me know if it happens again. I'll keep the issue open in case somebody else notice any similar issue.

*EDIT:* Just noticed that It's the header for those 2 stickers. I'll take a look.

*UPDATE:* I can confirm this issue. It happens when stickers are grouped. It'll be fixed in the next release. Thanks for reporting.

**Comment by m4heshd** [comment] 2020-02-27 22:14
Fixed in the latest release. Closing.

**Closed as completed by m4heshd** 2020-02-27 22:14 UTC
Labels: Bug 🐞, Fixed 🎉
