### ISSUE TITLE
Dialog boxes is white now...

### ISSUE THREAD

**Issue by mcsomenzari** [m4heshd/whatsapp-desktop-dark#57] opened 2019-10-04 17:20 UTC
![image](https://user-images.githubusercontent.com/29438629/66226702-d80f6c00-e6b1-11e9-8532-73a2972f837c.png)
After some Office or Windows update... I think.

**Comment by Ingenieurs** [comment] 2019-10-04 18:19
Fix is released
-> https://github.com/m4heshd/whatsapp-desktop-dark/releases/tag/0.3.4941

**Comment by m4heshd** [comment] 2019-10-04 18:20
Hi, This is a duplicate of issue #47 and closing this since the release with fix is out.

**Comment by mcsomenzari** [comment] 2019-10-04 18:21
👍

**Closed as completed by m4heshd** 2019-10-04 18:20 UTC
