### ISSUE TITLE
failed to inject style

### ISSUE THREAD

**Issue by Abhilashsj92** [m4heshd/whatsapp-desktop-dark#3] opened 2019-09-03 05:48 UTC
![image](https://user-images.githubusercontent.com/54832078/64146970-7c488d80-ce3c-11e9-9699-fec09335bb2c.png)

**Comment by Abhilashsj92** [comment] 2019-09-03 05:54
this is not working with Admin elevation also
![image](https://user-images.githubusercontent.com/54832078/64147250-5079d780-ce3d-11e9-972b-17e6df330aca.png)

**Comment by maximusapen** [comment] 2019-09-03 08:00
Yea I got the same issue on a Mac as well

<img width="1011" alt="Screenshot 2019-09-03 at 08 59 34" src="https://user-images.githubusercontent.com/41734177/64154725-4a79fb80-ce29-11e9-9960-bf1ca835bc6b.png">

**Comment by strandloper** [comment] 2019-09-03 08:04
Same error on Windows 10 x64. What I notice is that the version reported in the failure message is later than the one mentioned in the readme. However I would guess that a permission error would not be due to different versions.

**Comment by m4heshd** [comment] 2019-09-03 08:25
Hi @Abhilashsj92, Your issue is occurring because you have the Microsoft store version of WhatsApp desktop. Unfortunately the script won't work with that version since windows highly protect store installed applications. Please try it with the direct download from [this page](https://www.whatsapp.com/download). Really sorry for not mentioning this on the documentation. I will update it ASAP.

Hi @maximusapen, That's really weird. I'm unable to reproduce your issue. Did you install WhatsApp desktop from app store? If you did please remove that version and try it with the direct download version i have mentioned above. If you didn't, can you try to run the script from terminal with `sudo` as `sudo WADark` and let us know the result.

**Comment by alex4108** [comment] 2019-09-10 07:40
Using Mac OS 10.14 + WhatsApp from store
@maximusapen If you still have the store copy, I did a chmod on my store copy and that resolved the issue
`chmod -R 777 /Applications/Whatsapp.app `
and execution as user (not root) made it install

Many thanks!

**Comment by m4heshd** [comment] 2019-09-10 15:20
Hi @alex4108,
Thank you for the input. But i wouldn't recommend changing the ownership of a store installed application. The latest source contains few modifications that would allow you to run the script with `sudo` properly.

**Comment by m4heshd** [comment] 2019-10-04 19:31
Closing this because the thread isn't active anymore.

**Closed as completed by m4heshd** 2019-10-04 19:31 UTC
Labels: Known-issue, Workaround
