### ISSUE TITLE
New whatsapp version is broken

### ISSUE THREAD

**Issue by NicolasPL64** [m4heshd/whatsapp-desktop-dark#51] opened 2019-10-03 21:21 UTC
![image](https://user-images.githubusercontent.com/31411531/66165162-c4a0ca00-e5f9-11e9-9d0f-0347628b0ecf.png)

**Comment by NicolasPL64** [comment] 2019-10-03 21:23
![image](https://user-images.githubusercontent.com/31411531/66165273-06317500-e5fa-11e9-94d3-35ff018571b8.png)
also, I have 2 folders now (again) xD

**Comment by NicolasPL64** [comment] 2019-10-03 21:37
Sorry, I just noticed it was already posted. But what do I have to do for the "duplicated" folder?

**Comment by m4heshd** [comment] 2019-10-03 23:43
Hi @NicolasPL64,
The folders aren't duplicated. That's how squirrel manager handle updates. You got nothing to worry. And the original issue is a duplicate of issue #47 which is already fixed in the source in a5c729564ca108e8296003c381fdc301e85b0f91.  Releases will be available soon. Updates will be posted at https://t.me/wadarkmodechat.

**Closed as completed by m4heshd** 2019-10-03 23:43 UTC
