### ISSUE TITLE
Solid color bar behind sent messages' bubbles - started in 0.3.5148

### ISSUE THREAD

**Issue by UnderEu** [m4heshd/whatsapp-desktop-dark#94] opened 2019-11-06 02:45 UTC
As of new updates to official app, it began to appear a solid color bar behind every sent messages' bubbles. This occurs on every chat tab, rather direct contact or group.

Issue started on v0.3.5148, didn't test on latest release to date (v0.3.5374)
Tested on macOS.

Screenshot: ![2019-11-05 23 38 33](https://user-images.githubusercontent.com/16519758/68263965-25228d00-0026-11ea-80c8-1ba3878f8ff7.jpg)
*Content blurred due to privacy concerns

**Comment by Iroxxar** [comment] 2019-11-07 16:13
Can confirm for Version 0.3.5374 on Windows 10 too.

**Comment by NicolasPL64** [comment] 2019-11-11 20:22
Yeah, this is old but I don't know where is the developer: I think he is not in his city or something. I hope he hasn't left this project

**Comment by UnderEu** [comment] 2019-11-11 23:06
> Yeah, this is old but I don't know where is the developer: I think he is not in his city or something. I hope he hasn't left this project

He didn't, he's just too busy and w/o much time to provide updates to this one. In fact, this issue was opened because he asked me to.

Just be patient

**Comment by LMestre14** [comment] 2019-11-18 09:57
A colleague of mine solve that visual "bug".

basically in the .css file under /* Message bubbles. */
he substituted
`html[dir] .message-in ._2Wx_5, .message-out, .message {
    background-color: var(--darker) !important; }`

with

`html[dir] .message-in ._2Wx_5, .message {
    background-color: var(--darker) !important; }
html[dir] ._2Wx_5, .message-out, .message {
    background-color: transparent !important; }`

and it worked perfectly

**Comment by kaushiknadig** [comment] 2019-11-20 16:09
As @LMestre14 told it does temporarily solve it, but it seems like an issue with the border size for the outgoing message that has changed. Hence the whole window becomes the color we add for the outgoing message. With that temporary solution, the background for the outgoing message becomes transparent and so the wallpaper behind the message will be visible.
![Capture](https://user-images.githubusercontent.com/15876062/69255666-3a7ae800-0bde-11ea-91ad-a52ae6049df6.PNG)

**Comment by LMestre14** [comment] 2019-11-21 09:38
@kaushiknadig so apparently the **Pull Request number 85** has the "more correct" solution to this problem. If the maintainer accepts that, it will solve the problem for windows and macos



> A colleague of mine solve that visual "bug".
> 
> basically in the .css file under /* Message bubbles. */
> he substituted
> `html[dir] .message-in ._2Wx_5, .message-out, .message { background-color: var(--darker) !important; }`
> 
> with
> 
> `html[dir] .message-in ._2Wx_5, .message { background-color: var(--darker) !important; } html[dir] ._2Wx_5, .message-out, .message { background-color: transparent !important; }`
> 
> and it worked perfectly

And as the pull request shows, you only need these 2 lines

```
html[dir] .message-in ._2Wx_5 {
    background-color: var(--darker) !important; }
html[dir] .message-out ._2Wx_5 {
    background-color: var(--msgout) !important; }
```

**Comment by m4heshd** [comment] 2020-02-01 11:16
Closing this since the issue is a duplicate of #77 and has been fixed in the latest release.

**Closed as completed by m4heshd** 2020-02-01 11:16 UTC
Labels: Duplicate
