### ISSUE TITLE
Replied messages have light backgrounds instead of dark

### ISSUE THREAD

**Issue by marcelo-mason** [m4heshd/whatsapp-desktop-dark#140] opened 2020-02-20 05:21 UTC
![image](https://user-images.githubusercontent.com/577340/74903440-ef0bdd80-5376-11ea-911d-ce8b6fb050c5.png)

**Comment by m4heshd** [comment] 2020-02-20 05:45
Closing since a duplicate of #139.

**Closed as completed by m4heshd** 2020-02-20 05:45 UTC
Labels: Duplicate
