### ISSUE TITLE
Whatsapp background has black bars on my messages

### ISSUE THREAD

**Issue by LookAtDeezShots** [m4heshd/whatsapp-desktop-dark#77] opened 2019-10-18 08:00 UTC
Hey, I got this issue, that my messages got black bars on the background.
It looks like this: 
![image](https://user-images.githubusercontent.com/36506224/67076670-e9ff0d80-f18d-11e9-9eb8-433fb913acab.png)

Now I don't know if there is something wrong with my whatsapp or not, but any advice would help.

Thanks for helping!

**Comment by reformedot** [comment] 2019-10-18 15:09
Same problem here

**Comment by Rychillie** [comment] 2019-10-19 03:38
Same problem here

**Comment by SantiagoITHS** [comment] 2019-10-19 15:28
Same problem here;

Thought it could be the transparecy of the message box background.


Tested on macOS Catalina and Mojave both, latest releases.

**Comment by haveneersrobin** [comment] 2019-10-23 12:49
My two cents: the class ".bg_chat" is not targeted in the css for the dark theme but I believe it's that class that provides the bg color to replies?

Only replies are affected, fyi

**Comment by reformedot** [comment] 2019-10-23 16:01
Seems that replies have a parameter that sent messages don't have, to set background as transparent.

**Comment by Goldsucher** [comment] 2019-10-23 22:15
same problem here after experimenting with own style. Does someone know how to get rid of it? Rerun the script with default overright.json and reinstalling whatsapp doesn't help.
Running MacOS Catalina.

Thanks in advance

**Comment by lasmaty07** [comment] 2019-10-25 13:49
same problem here

**Comment by juanpcabrera17** [comment] 2019-10-25 15:34
Same here. Maybe the "dark" theming code file can be modified but idk which element is that "black bar".

**Comment by Artemkiin** [comment] 2019-10-28 10:41
Same problem, Windows 10.

**Comment by jweber018** [comment] 2019-10-28 16:19
Hey, I managed to somewhat fix this by changing the background of the messages to transparent. I modified the dark.css under styles. I'll attach it, give it a try.


`/* Message bubbles. */
html[dir] .message-in ._2Wx_5, .message-out, .message {
    background-color: transparent !important; }
html[dir] .message-out ._2Wx_5 {
    background-color: var(--msgout) !important; }
/* Deleted messages */
._3uHCS, ._2v02G {
    color: var(--light) !important;
    opacity: 0.70;
}`

Replace line 590 to line 599 with this.

**Comment by Artemkiin** [comment] 2019-10-28 18:59
> 
> 
> Hey, I managed to somewhat fix this by changing the background of the messages to transparent. I modified the dark.css under styles. I'll attach it, give it a try.
> 
> `/* Message bubbles. */ html[dir] .message-in ._2Wx_5, .message-out, .message { background-color: transparent !important; } html[dir] .message-out ._2Wx_5 { background-color: var(--msgout) !important; } /* Deleted messages */ ._3uHCS, ._2v02G { color: var(--light) !important; opacity: 0.70; }`
> 
> Replace line 590 to line 599 with this.

Hello!
Thanks for Your trying to help, but it didn't work :(

**Comment by Goldsucher** [comment] 2019-10-28 19:02
thx for the idea @jweber018 ! The problem with your approach (for me) was, that the incoming message bubbles have the same color as the background image.
In my approach, I just removed the classes .message-out and .message, which brought back the expected behaviour at first glance:

`/* Message bubbles. */ 
html[dir] .message-in ._2Wx_5 { 
    background-color: var(--darker) !important; 
} 
html[dir] .message-out ._2Wx_5 { 
    background-color: var(--msgout) !important; 
} `

**Comment by Artemkiin** [comment] 2019-10-28 19:09
> 
> 
> thx for the idea @jweber018 ! The problem with your approach (for me) was, that the incoming message bubbles have the same color as the background image.
> In my approach, I just removed the classes .message-out and .message, which brought back the expected behaviour at first glance:
> 
> `/* Message bubbles. */ html[dir] .message-in ._2Wx_5 { background-color: var(--darker) !important; } html[dir] .message-out ._2Wx_5 { background-color: var(--msgout) !important; } `

Tried this variant too. Still not working :(

**Comment by Goldsucher** [comment] 2019-10-28 19:11
did you re-run the script?

**Comment by Artemkiin** [comment] 2019-10-28 19:12
Sure, restored WhatsApp to default version, change code in dark.css and then tried.

**Comment by juanpcabrera17** [comment] 2019-10-28 19:22
I deleted the classes `.message-out` and `.message` and now it's working fine for me. Thanks!

**Comment by Artemkiin** [comment] 2019-10-28 20:18
> /* Message bubbles. */ html[dir] .message-in ._2Wx_5 { background-color: var(--darker) !important; } html[dir] .message-out ._2Wx_5 { background-color: var(--msgout) !important; }

Looked a little bit lower and see that code on lines 607-616 -_-
This changes removed a black bars, but in this case i have another problem, text looks like at this screen: 
![изображение](https://user-images.githubusercontent.com/29740726/67714389-dc8d2300-f9d8-11e9-8ffd-70d515fdc010.png)

And how i can see — your code that's it is solution for issue with a unreadable lightgray text on unchanged bubbles o_0

**Comment by Artemkiin** [comment] 2019-10-28 20:32
In any case i have one of two problems: Black bars or lightgraytext on green background bubbles =/

**Comment by juanpcabrera17** [comment] 2019-10-28 20:49
> > /* Message bubbles. */ html[dir] .message-in ._2Wx_5 { background-color: var(--darker) !important; } html[dir] .message-out ._2Wx_5 { background-color: var(--msgout) !important; }
> 
> Looked a little bit lower and see that code on lines 607-616 -_-
> This changes removed a black bars, but in this case i have another problem, text looks like at this screen:
> ![изображение](https://user-images.githubusercontent.com/29740726/67714389-dc8d2300-f9d8-11e9-8ffd-70d515fdc010.png)
> 
> And how i can see — your code that's it is solution for issue with a unreadable lightgray text on unchanged bubbles o_0

i had the exact same problem but i fixed it by deleting the classes `.message-out` and `.message` in the original dark.css file at `/* messages bubbles` as Goldsucher suggested. Don't modify anything else, otherwise it will look as the picture you've posted.

`/* Message bubbles. */
html[dir] .message-in .Nxkz1 {
    background-color: var(--darker) !important; }
html[dir] .message-out .Nxkz1 {
    background-color: var(--msgout) !important; }
`

**Comment by Artemkiin** [comment] 2019-10-28 21:50
> 
> 
> > > /* Message bubbles. */ html[dir] .message-in ._2Wx_5 { background-color: var(--darker) !important; } html[dir] .message-out ._2Wx_5 { background-color: var(--msgout) !important; }
> > 
> > 
> > Looked a little bit lower and see that code on lines 607-616 -_-
> > This changes removed a black bars, but in this case i have another problem, text looks like at this screen:
> > ![изображение](https://user-images.githubusercontent.com/29740726/67714389-dc8d2300-f9d8-11e9-8ffd-70d515fdc010.png)
> > And how i can see — your code that's it is solution for issue with a unreadable lightgray text on unchanged bubbles o_0
> 
> i had the exact same problem but i fixed it by deleting the classes `.message-out` and `.message` in the original dark.css file at `/* messages bubbles` as Goldsucher suggested. Don't modify anything else, otherwise it will look as the picture you've posted.
> 
> `/* Message bubbles. */ html[dir] .message-in .Nxkz1 { background-color: var(--darker) !important; } html[dir] .message-out .Nxkz1 { background-color: var(--msgout) !important; } `

I don't know, what i was doing wrong, but im tried many variants and in each i was having any problems.

But at this time i just copied all code from original dark.css at GitHub and pasted your code into it, and finally it works as it should! Thank You very much!

**Comment by haveneersrobin** [comment] 2019-10-29 09:39
I filed a pull request with your fix @Goldsucher (bumping @m4heshd )

**Comment by benthuss** [comment] 2019-11-05 16:33
> thx for the idea @jweber018 ! The problem with your approach (for me) was, that the incoming message bubbles have the same color as the background image.
> In my approach, I just removed the classes .message-out and .message, which brought back the expected behaviour at first glance:
> 
> `/* Message bubbles. */ html[dir] .message-in ._2Wx_5 { background-color: var(--darker) !important; } html[dir] .message-out ._2Wx_5 { background-color: var(--msgout) !important; } `

This worked for me!

**Comment by m4heshd** [comment] 2020-01-31 22:05
Closing this since this issue has been fixed in the latest release.

**Closed as completed by m4heshd** 2020-01-31 22:05 UTC
Labels: Bug 🐞, Fixed 🎉
