### ISSUE TITLE
Text message is not readable on MacOS

### ISSUE THREAD

**Issue by vitinhosessa** [m4heshd/whatsapp-desktop-dark#47] opened 2019-10-03 03:13 UTC
![Captura de Tela 2019-10-03 às 00 10 03](https://user-images.githubusercontent.com/41197767/66096755-6c72b500-e572-11e9-94fb-970c20ff7ff1.png)

How can i fix that?

My Mac is on 10.14.5 Mojave, and WhatsApp is on version 0.3.4941

**Comment by Megameatloaf** [comment] 2019-10-03 07:36
Having the same issue
I tried going through some of the files and looking for where it specifies the text color but I don't understand enough about the way its coded to have a clue what to change, I can't see anything obvious like html color codes or something simple
![image](https://user-images.githubusercontent.com/56082793/66107830-8957c880-e604-11e9-847f-8bfaf7ee8615.png)

**Comment by lucasff** [comment] 2019-10-03 08:37
I have the same issue! horrible!

**Comment by joshuacheww** [comment] 2019-10-03 09:09
<img width="291" alt="Untitled" src="https://user-images.githubusercontent.com/56111539/66114031-9377c800-e600-11e9-8bb5-ebdf9dccdeaf.png">

Please fix it!!!

**Comment by kishore-vkrn** [comment] 2019-10-03 12:51
Same issue here!

**Comment by Arcanide** [comment] 2019-10-03 13:10
same issue here also on win10

**Comment by tueksta** [comment] 2019-10-03 14:53
They released a new version 0.3.4940 on Mac App Store 2 days ago. Since then it's broken as described above. One quick solution is to use an older version if you find one on the www, like https://whatsapp-desktop.en.uptodown.com/mac/versions

**Comment by HillTravis** [comment] 2019-10-03 15:03
@tueksta Thanks for the workaround. It works, but then it always shows the bright "Update available" notification, which is still an eyegore with the dark background.

Hoping for an official fix soon!

**Comment by m4heshd** [comment] 2019-10-03 16:13
We're aware of this and It'll be fixed soon. Update was just released so it takes time to debug and rebuild. You all can stay in the loop at https://t.me/wadarkmodechat.

**Comment by Ktklein72** [comment] 2019-10-03 20:26
> same issue here also on win10

I can confirm same issue on Win10.  Thought I broke something reinstalled WA Desktop and WA Dark Mode a few times and same behavior.  Should have check here first!

**Comment by NicolasPL64** [comment] 2019-10-03 21:38
Same on Win10

**Comment by Ktklein72** [comment] 2019-10-03 22:28
Maybe the title of this thread should be changed to show Mac OS and Win10 both...

**Comment by blu2b** [comment] 2019-10-03 23:24
my current workaround if you love the dark version as much as me and don't want to wait for the fix:
1. go into the WADark folder and and then **styles>darwin**
2. open **dark.css** with an editor (e.g. atom for mac, notepad++ for Win)
3. change **line 605** from `color: var(--light) !important; }`  into `    color: var(--dark) !important; }`
4. save the changes and rerun the execution file **WADark**

There are still some other parts that are colored wrong but this should make text readable again for you!

**Comment by m4heshd** [comment] 2019-10-03 23:45
Issue is already fixed in a5c729564ca108e8296003c381fdc301e85b0f91. Not available on release yet till the tests are done. You can clone the repo and build the source if interested. Updates will be posted on Telegram. 

Also the new beta supports custom theming. Check https://github.com/m4heshd/whatsapp-desktop-dark/tree/master/themes. Download and place any `override.json` file right next to WADark before installation to test.

**Comment by vitinhosessa** [comment] 2019-10-04 00:32
Thanks a lot @m4heshd 😄

**Comment by NicolasPL64** [comment] 2019-10-04 00:48
Thanks bro! <3

**Comment by NicolasPL64** [comment] 2019-10-04 00:56
![image](https://user-images.githubusercontent.com/31411531/66173816-bd88b480-e617-11e9-98d7-97146be22a6c.png)
everything fine now :D

**Comment by m4heshd** [comment] 2019-10-04 02:46
Great. Give it another update. More features added. 🙂

**Comment by vatologic** [comment] 2019-10-04 08:08
Just here to confirm the white/green text bubbles on MacOS. I'll give the manual override / older version of Whatsapp Desktop described above a go.

**WhatsApp**
Source: Non-App store / direct download
Version: 0.3.4941
Script:  0.3.4678

**MacOS**
10.14.6 (18G95)

**Comment by HillTravis** [comment] 2019-10-04 17:41
Correcting @blu2b's solution using the official solution provided by @m4heshd (if you don't want to wait for the official release or build from scratch):

* go into the WADark folder and and then **styles>darwin**
* open **dark.css** with an editor (e.g. atom for mac, notepad++ for Win)
* change **line 587** from `.message-in, .message-out, .message {`  into `html[dir] .message-in ._2Wx_5, .message-out, .message {`
* change **line 589** from `.message-out {` into `html[dir] .message-out ._2Wx_5 {`
* save the changes and rerun the execution file **WADark**

**Comment by m4heshd** [comment] 2019-10-04 18:17
Closing this since the issue has been fixed and the release is out now. 🎉

**Closed as completed** 2019-10-04 18:18 UTC
Labels: Bug 🐞, Fixed 🎉
