### ISSUE TITLE
Chat bubbles dont change colour, making the text unreadable

### ISSUE THREAD

**Issue by imblakeluna** [m4heshd/whatsapp-desktop-dark#48] opened 2019-10-03 14:30 UTC
App updated itself (Version 0.3.4941), Windows 10, when I ran the script the green chat bubbles didnt change but everything else did. The text being white makes it almost impossible to use.

Thanks for making this app and hope this isnt too hard to fix!

**Comment by KeronCyst** [comment] 2019-10-03 16:01
Confirmed. I couldn't tolerate CTRL+A'ing all the time to read, and had to remove Dark Mode.

**Comment by m4heshd** [comment] 2019-10-03 16:14
@imblakeluna This is a duplicate of issue #47 and It's already acknowledged. It'll be fixed soon.

**Closed as completed** 2019-10-03 16:15 UTC
Labels: Duplicate
