### ISSUE TITLE
Unable to run WADark script in macOS

### ISSUE THREAD

**Issue by justinlee979** [m4heshd/whatsapp-desktop-dark#91] opened 2019-11-05 13:40 UTC
![image](https://user-images.githubusercontent.com/57401849/68212617-d5879580-0014-11ea-941d-cc23c055125a.png)

Every time I double click WADark, it just opens it in TextEdit. I am not able to run it in Script Editor

**Comment by UnderEu** [comment] 2019-11-06 02:53
Follow these steps:
- Open the WA app;
- Open Terminal;
- Type: `chmod +x` [drag the WADark file into the Terminal window] [Hit Return/Enter];

then

- [drag the WADark file into the Terminal window] [Hit Return/Enter];
- Follow the instructions on screen;
- Bless your eyes.

@m4heshd Add those in a README.txt among macOS bundle.

**Comment by justinlee979** [comment] 2019-11-06 10:11
After dragging the WADark file in and hitting enter, it says 'permission denied'

**Comment by justinlee979** [comment] 2019-11-06 10:15
Managed to get it to work after following your steps. Thank you!

**Comment by m4heshd** [comment] 2020-02-01 11:12
Closing this since the issue is solved.

**Closed as completed by m4heshd** 2020-02-01 11:12 UTC
Labels: External-issue, Solved 👍
