### ISSUE TITLE
Whatsapp symbol blocking QR code

### ISSUE THREAD

**Issue by MaiaMedeiros** [m4heshd/whatsapp-desktop-dark#133] opened 2020-02-05 15:30 UTC
Dear m4heshd
After installing the dark theme (that worked well), however, the WhatsApp symbol appeared over the QR code (to open at MacBook) difficulting the camera to read it.
Any idea how to resolve it?
Best,
![Screen Shot 2020-02-05 at 12 20 33](https://user-images.githubusercontent.com/37161733/73855714-393b7d80-4813-11ea-8e07-db546bcf23c1.png)

**Comment by m4heshd** [comment] 2020-02-05 21:42
Hi @MaiaMedeiros,
Are you using the "Deep Black" theme? Having the logo in middle doesn't affect the functionality at all. But what can be causing trouble is not having a white border around that QR code. Doesn't it have that border or did you crop it out from the screenshot by any chance?

**Comment by MaiaMedeiros** [comment] 2020-02-05 21:47
Hi @m4heshd, 
I installed the deep black theme however, my phone didn't recognize the QR code. 
There isn't a white border at all.
I can try to install another theme to see if works.
Follow another screenshot to you to check.

![Screen Shot 2020-02-05 at 18 46 57](https://user-images.githubusercontent.com/37161733/73886243-f6e06380-4847-11ea-9f18-49561097933c.png)

**Comment by chasewinnings391** [comment] 2020-02-06 12:57
Can confirm. I had the same issue. Workaround was to disable the theme, scan QR-code and log-in, and re-enable the dark theme.

**Comment by m4heshd** [comment] 2020-02-08 00:32
That's really weird because we specifically talked about this issue on the Telegram chat and was fixed. 32ca3c41534faa180678602dd7e762a0caa5d9ce this commit to be exact.

**Comment by UnderEu** [comment] 2020-02-08 00:47
It's working fine, for me
WA v0.4.612 + WADark v0.4.315 - macOS

![Screen Shot 2020-02-07 at 21 44 56](https://user-images.githubusercontent.com/16519758/74075841-72cadf00-49f3-11ea-81b3-49808bf07055.png)

**Comment by RuggeDX** [comment] 2020-02-08 13:18
Just uninstall the theme, log in, then install the theme again as a workaround :)

**Comment by MaiaMedeiros** [comment] 2020-02-10 14:34
Thanks, guys. I will try this way.

**Comment by m4heshd** [comment] 2020-02-10 21:15
Hi @MaiaMedeiros, I've confirmed this on multiple mac users and there's no actual issue if you're using correct versions. I can tell by your screenshot that you seem to be using an older version or some modified version of WADark. The WhatsApp logo on that QR code should have the accent color instead of that dark color if you were using the correct versions. Please reinstall WD and download the latest release of WADark.

**Comment by purplpasta** [comment] 2020-02-22 18:24
I fixed it by taking a screenshot, cropping the QR code (so there is no border) and scanning it then

This can also be done with programs like Snipping Tool

**Comment by m4heshd** [comment] 2020-02-27 22:12
Closing this.

**Closed as completed by m4heshd** 2020-02-27 22:12 UTC
Labels: Not-an-issue 🚫, Solved 👍
