### ISSUE TITLE
Having All Text Grey Latest Update

### ISSUE THREAD

**Issue by arslanejaz33** [m4heshd/whatsapp-desktop-dark#55] opened 2019-10-04 14:25 UTC
Installed the new update today, the text went all grey and barely unreadable. Tried reinstalling wadark and Whatsapp desktop also, but they remain the same.

![Annotation 2019-10-04 192237](https://user-images.githubusercontent.com/21056479/66215286-abbd1500-e6dc-11e9-9b90-b925bb55da03.png)

**Comment by kumode** [comment] 2019-10-04 14:27
Can confirm - whatsapp dekstop windows 64 bit.
![image](https://user-images.githubusercontent.com/42411026/66215486-4cef9f80-e6cc-11e9-9d03-77436aa6c425.png)

**Comment by m4heshd** [comment] 2019-10-04 14:43
Hi @arslanejaz33,
This is a duplicate of issue #47 and updates are available there.

**Closed as completed by m4heshd** 2019-10-04 14:43 UTC
Labels: Duplicate
