### ISSUE TITLE
Text color in messaging bar not changed

### ISSUE THREAD

**Issue by hexx1001** [m4heshd/whatsapp-desktop-dark#146] opened 2020-02-25 02:05 UTC
![image](https://user-images.githubusercontent.com/50043926/75208240-f89da700-57b5-11ea-9c75-aa1f81aacdbb.png)

Tried applying different themes but the text color for messaging is too dark for the dark background. On WhatsApp 0.4.930.

**Comment by m4heshd** [comment] 2020-02-25 02:12
Closing because it's a duplicate of #139.

**Closed as completed by m4heshd** 2020-02-25 02:12 UTC
Labels: Duplicate
