### ISSUE TITLE
Interface is not as it shown in your thread, colors are mixed up

### ISSUE THREAD

**Issue by fahadsabri** [m4heshd/whatsapp-desktop-dark#116] opened 2020-01-21 10:37 UTC
![image](https://user-images.githubusercontent.com/46475612/72797940-13c74500-3c53-11ea-91d6-30fbc391a5f5.png)

**Comment by romskidd** [comment] 2020-01-21 12:38
There has been an update of whatsapp few days ago that make the interface like this, you just need to wait for an update.

**Comment by snorreflorre** [comment] 2020-01-21 13:31
Duplicate of #114

**Comment by m4heshd** [comment] 2020-02-01 11:25
Closing this since the issue is a duplicate of #113 and has been fixed in the latest release.

**Closed as completed by m4heshd** 2020-02-01 11:25 UTC
Labels: Duplicate
