### ISSUE TITLE
Style bug? Windows 10

### ISSUE THREAD

**Issue by OficialneMON** [m4heshd/whatsapp-desktop-dark#56] opened 2019-10-04 15:55 UTC
![image](https://user-images.githubusercontent.com/20894181/66221860-dcca2500-e69d-11e9-898a-1e2472c5a510.png)

**Comment by mcsomenzari** [comment] 2019-10-04 17:22
Same with me... I think it was after some Office or Windows update ...

**Comment by m4heshd** [comment] 2019-10-04 18:19
Hi, This is a duplicate of issue #47 and closing this since the release with fix is out.

**Closed as completed by m4heshd** 2019-10-04 18:19 UTC
Labels: Duplicate
