### ISSUE TITLE
Mention of message without CSS

### ISSUE THREAD

**Issue by patrickxfranco** [m4heshd/whatsapp-desktop-dark#145] opened 2020-02-24 01:45 UTC
Mentioned messages are without application of the style, as in the image

![Error](https://user-images.githubusercontent.com/52086621/75124453-1ec82780-568e-11ea-840d-8f04b2b3fbb3.PNG)

**Comment by m4heshd** [comment] 2020-02-24 01:47
Closing because the issue is a duplicate of #139.

**Closed as completed by m4heshd** 2020-02-24 01:47 UTC
Labels: Duplicate
