### ISSUE TITLE
this happen to me to

### ISSUE THREAD

**Issue by JOKERMERONI** [m4heshd/whatsapp-desktop-dark#190] opened 2020-04-03 10:56 UTC
![image](https://user-images.githubusercontent.com/63080288/78353564-eda71500-75b2-11ea-8dd3-a51002465d19.png)

**Comment by Shuja-Mahmood** [comment] 2020-04-03 15:30
Duplicate of #172

**Comment by JOKERMERONI** [comment] 2020-04-04 00:13
yes

**Comment by UnderEu** [comment] 2020-04-04 17:19
Duplicate issue. See #172 for further information

**Closed as completed by UnderEu** 2020-04-04 17:19 UTC
Labels: Duplicate
