### ISSUE TITLE
Error while applying theme 

### ISSUE THREAD

**Issue by EmirSc** [m4heshd/whatsapp-desktop-dark#58] opened 2019-10-04 21:40 UTC
![explorer_MBFE02nG1g](https://user-images.githubusercontent.com/8141067/66241809-2118ed80-e6bd-11e9-90cb-f4d61d2061de.png)

installed ver.0.3.4941 (no problems)
downloaded themes
renamed override.json to override original.json
renamed override.json (from themes deepblack)
run WADark.exe

**Comment by Slyther** [comment] 2019-10-05 02:54
I can't reproduce your error. Did exactly what you said you did.

![image](https://user-images.githubusercontent.com/4093602/66248840-cac1a400-e6e8-11e9-9b86-6741169f80c5.png)

The method JSON.parse is finding an unexpected token in your JSON file. Perhaps you accidentally added something to it? Check the JSON's validity by pasting the JSON text here and clicking "Validate JSON": https://jsonlint.com/

EDIT: Also noticed both your override JSON and Telegram JSON weigh 93KB, so you definitely did something other than just renaming the file (original size should be 1KB).

**Comment by m4heshd** [comment] 2019-10-05 08:19
@EmirSc, as @Slyther mentioned, something must've modified your JSON files. Please re-download and test.

**Comment by EmirSc** [comment] 2019-10-05 15:37
thank you, verified the content of the json, and was all nonsense (i right click download each json is that the correct way), had to pase the content inside every downloaded file and now it works

**Comment by m4heshd** [comment] 2019-10-05 18:01
Oh that's the issue. It's not the JSON file gets downloaded when you do that. It's an HTML. Click on the JSON file and then you have to click on the `Raw` button to download the original file.

![image](https://user-images.githubusercontent.com/6711514/66258886-02534d80-e7c8-11e9-8d9f-124e4f45981c.png)


Closing the issue.

**Closed as completed by m4heshd** 2019-10-05 18:01 UTC
Labels: Not-an-issue 🚫, Solved 👍
