### ISSUE TITLE
Voice Note Playback Bar Style Issue

### ISSUE THREAD

**Issue by Slyther** [m4heshd/whatsapp-desktop-dark#20] opened 2019-09-08 05:33 UTC
The voice note bar for sent voice notes has a green-ish background. Probably not the same bar as the one used for received voice notes.

Sent VN:

![voice note green-ish bar](https://user-images.githubusercontent.com/4093602/64483877-726db400-d1c7-11e9-8840-1b61e3f92a3e.png)

Received VN for comparison:

![voice note white bar](https://user-images.githubusercontent.com/4093602/64483905-e445fd80-d1c7-11e9-95bf-068912105f0b.png)

**Comment by m4heshd** [comment] 2019-09-08 08:32
Hi @Slyther,
I can reproduce this issue and it will be fixed in the next release. Thank you for reporting.

**Comment by spuyelli** [comment] 2019-09-08 17:43
Adding to this issue, I'd suggest changing the color of the audio icon to the respective colors (gray, green, blue) in-chat, and also the little icons where the chats are listed:

![Sin título](https://user-images.githubusercontent.com/19256015/64492056-fcf4f880-d245-11e9-9d66-82b4e44a5409.png)

I managed to change the ones in the chat, but couldn't those in the chat list.

BTW, awesome work man!

**Comment by m4heshd** [comment] 2019-09-09 02:02
Hi @spuyelli,
Thanks for the suggestion. I personally think the first one which has the darker color looks good. Let me do some tests before the next release.

**Comment by m4heshd** [comment] 2019-09-23 01:02
Hi @Slyther, the issue you raised is fixed in f3b8af0fe72be3ecad3b7c4dc5a9c72f5ecf545c and available in the latest release. Unfortunately @spuyelli i didn't go with the suggestion because tests revealed that current version of the icon looks much cleaner and noticeable. Since the majority preferred the current version i left it as it is. Sorry about that. Closing the issue.

**Closed as completed by m4heshd** 2019-09-23 01:02 UTC
Labels: Bug 🐞, Fixed 🎉
