### ISSUE TITLE
Sent messages have a full width background

### ISSUE THREAD

**Issue by FPSUsername** [m4heshd/whatsapp-desktop-dark#112] opened 2020-01-12 16:13 UTC
As you can see in the picture, my sent message has a full width background. Currently running whatsapp v0.3.9309 from the MS store. Even though the readme states that it doesn't work with the store app, it pretty much does apart from this bug.

![Sent_bug](https://user-images.githubusercontent.com/10143926/72221842-a0407c00-355e-11ea-98df-08c0b7bc8f4e.png)

**Comment by mattiascaricato** [comment] 2020-01-12 22:47
+1

**Comment by magical-inference** [comment] 2020-01-14 08:40
+1, version 0.3.9309, only happens to my own messages (not to those I received):


![image](https://user-images.githubusercontent.com/21123524/72327612-be6ac100-36b1-11ea-9c65-75eb67a343c5.png)

**Comment by Shuja-Mahmood** [comment] 2020-01-23 11:59
Duplicate of #94

**Comment by m4heshd** [comment] 2020-02-01 11:20
Closing this since the issue is a duplicate of #77 and has been fixed in the latest release.

**Closed as completed by m4heshd** 2020-02-01 11:20 UTC
Labels: Duplicate
