### ISSUE TITLE
Reply "Quotes" on MacOS are white + fix

### ISSUE THREAD

**Issue by raphaelluethy** [m4heshd/whatsapp-desktop-dark#152] opened 2020-02-27 12:38 UTC
On macOS, if you reply to an answer, the "quoted" Msg will have a white background.

Adding 
```css
._3LVMN {
    background-color: var(--dark) !important;
    color: var(--light) !important;
}
```
to the styles/dark.css file fixed the problem for me :)

PS: Love your mod!

Cheers

Edit: I also found a "bug" where the typed text in the chatbox was grey, adding
```css
._3u328 {
    color: var(--lighter) !important;
}
```

fixed it too

**Comment by rmpll** [comment] 2020-02-27 12:45
where did you add the Lines? Im on Windows and I added them at the end of the File and it didn't change anything

**Comment by raphaelluethy** [comment] 2020-02-27 12:50
> where did you add the Lines? Im on Windows and I added them at the end of the File and it didn't change anything

i added them on line 145, but i dont think it should make a big difference

**Comment by m4heshd** [comment] 2020-02-27 22:08
Hi @rakocs, Glad you're enjoying my work and appreciate your effort. But this is a duplicate of #139 and fixed in the latest release. Closing.

**Closed as completed by m4heshd** 2020-02-27 22:08 UTC
Labels: Duplicate
