### ISSUE TITLE
Some styles have mixed up, parts are still white

### ISSUE THREAD

**Issue by JoelleVoogt** [m4heshd/whatsapp-desktop-dark#184] opened 2020-03-30 19:21 UTC
I think that some styles have mixed up.

The weird thing is that it has worked before (it worked absolutely great!). Everything was looking nice and dark, I could switch the types of dark modes (or even back to light mode) via a single button. I loved it.

But then, from one to the other day I realized that everything looked different, like the image.
I uninstalled everything. Deleted the whatsapp application.
And then redid the whole thing.

Download the official application.
Start up the application while unzipping, activating the .exe and installing.
Then close the application and let it replace the files and so forth.

I've tried this 4 times now.

I'm not an expert so I also don't really know what the problem here is.
I can only tell you what I have already done.

Can someone please help me with this?

I really loved the theme!
Thank you so much devs for making whatsapp easier on my eyes :D but now pleaaase bring it back!

![somestylesmixedup](https://user-images.githubusercontent.com/43187615/77952395-df63ab00-72cb-11ea-9f12-0783603a4658.png)

**Comment by rmadaan3** [comment] 2020-03-30 19:39
Duplicate issue. See #172 for further information

**Comment by rmadaan3** [comment] 2020-03-30 19:40
Duplicate of #172

**Comment by JoelleVoogt** [comment] 2020-03-30 19:47
Thanks for the quick response! I'm trying it right now. I'll keep you updated.

**Comment by JoelleVoogt** [comment] 2020-03-30 19:48
It worked 💃

**Comment by UnderEu** [comment] 2020-03-30 23:02
Duplicate issue. See #172 for further information

**Closed as completed by UnderEu** 2020-03-30 23:02 UTC
Labels: Duplicate
