### ISSUE TITLE
`npm install` fails on MacOS with "TypeError: Cannot read property 'protocol' of undefined"

### ISSUE THREAD

**Issue by tsanikgr** [m4heshd/whatsapp-desktop-dark#25] opened 2019-09-13 12:04 UTC
Building from source fails on my MacOS Mojave 10.14.4:

```console
 ➜ /tmp/whatsapp-desktop-dark git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   package-lock.json
	modified:   package.json

no changes added to commit (use "git add" and/or "git commit -a")
 ➜ /tmp/whatsapp-desktop-dark git checkout package.json
 ➜ /tmp/whatsapp-desktop-dark npm install

> resourcehacker@4.2.51 postinstall /private/tmp/whatsapp-desktop-dark/node_modules/resourcehacker
> node scripts/install.js

Downloading ResourceHacker by Angus Johnson...
_http_client.js:131
  var expectedProtocol = defaultAgent.protocol;
                                      ^

TypeError: Cannot read property 'protocol' of undefined
    at new ClientRequest (_http_client.js:131:39)
    at request (http.js:44:10)
    at Object.get (http.js:48:15)
    at Object.<anonymous> (/private/tmp/whatsapp-desktop-dark/node_modules/resourcehacker/scripts/install.js:23:20)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! resourcehacker@4.2.51 postinstall: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the resourcehacker@4.2.51 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ntsaou/.npm/_logs/2019-09-13T11_59_45_779Z-debug.log
```

Since I am on Mac, I removed the line `"resourcehacker": "4.2.51"` from `package.json` and everything works. Amazing work, thank you :)

Unfortunately, I have not worked with `node` or `npm`, so I do not how to create different `package.json` files for the 2 platforms.

**Comment by m4heshd** [comment] 2019-09-13 15:21
Hi @tsanikgr, 
This seems to be a duplicate of https://github.com/m4heshd/whatsapp-desktop-dark/issues/11. The error is thrown by the module you mentioned because It's only meant for the Windows build. You don't need to remove the module from package.json. You can just ignore the error. Either way glad you managed to work it out. Closing the issue.

**Closed as completed by m4heshd** 2019-09-13 15:21 UTC
Labels: Duplicate, Not-an-issue 🚫
