### ISSUE TITLE
Issues in installing

### ISSUE THREAD

**Issue by YuvalYarmus** [m4heshd/whatsapp-desktop-dark#137] opened 2020-02-13 23:05 UTC
`Error: EPERM: operation not permitted, unlink 'C:\Program Files\WindowsApps\5319275A.WhatsAppDesktop_0.4.315.0_x64__cv1g1gvanyjgm\app\resources\app.asar'
    at Object.unlinkSync (fs.js:1018:3)
    at mayCopyFile (C:\Users\Yuval Yarmus\Downloads\WADark-0.4.315-Windows\WADark-Windows\node_modules\fs-extra\lib\copy-sync\copy-sync.js:59:8)
    at onFile (C:\Users\Yuval Yarmus\Downloads\WADark-0.4.315-Windows\WADark-Windows\node_modules\fs-extra\lib\copy-sync\copy-sync.js:54:10)
    at getStats (C:\Users\Yuval Yarmus\Downloads\WADark-0.4.315-Windows\WADark-Windows\node_modules\fs-extra\lib\copy-sync\copy-sync.js:48:44)
    at startCopy (C:\Users\Yuval Yarmus\Downloads\WADark-0.4.315-Windows\WADark-Windows\node_modules\fs-extra\lib\copy-sync\copy-sync.js:38:10)
    at handleFilterAndCopy (C:\Users\Yuval Yarmus\Downloads\WADark-0.4.315-Windows\WADark-Windows\node_modules\fs-extra\lib\copy-sync\copy-sync.js:33:10)
    at Object.copySync (C:\Users\Yuval Yarmus\Downloads\WADark-0.4.315-Windows\WADark-Windows\node_modules\fs-extra\lib\copy-sync\copy-sync.js:26:10)
    at restoreBackup (C:\Users\Yuval Yarmus\Downloads\WADark-0.4.315-Windows\WADark-Windows\run-win32.js:156:12)
    at C:\Users\Yuval Yarmus\Downloads\WADark-0.4.315-Windows\WADark-Windows\run-win32.js:51:25
    at C:\Users\Yuval Yarmus\Downloads\WADark-0.4.315-Windows\WADark-Windows\node_modules\ps-node\lib\index.js:183:7 {
  errno: -4048,
  syscall: 'unlink',
  code: 'EPERM',
  path: 'C:\\Program Files\\WindowsApps\\5319275A.WhatsAppDesktop_0.4.315.0_x64__cv1g1gvanyjgm\\app\\resources\\app.asar'
}`

**Comment by m4heshd** [comment] 2020-02-13 23:09
Please read the documentation before installing. Closing because this is a duplicate of #3.

**Closed as completed by m4heshd** 2020-02-13 23:09 UTC
Labels: Duplicate
