### ISSUE TITLE
The messages that I send and I receive are with background white and the text gray like this

### ISSUE THREAD

**Issue by lucaslgr** [m4heshd/whatsapp-desktop-dark#84] opened 2019-10-26 00:04 UTC
![Capturar](https://user-images.githubusercontent.com/30275723/67610723-0c36f380-f76b-11e9-8c54-06870f626ef4.JPG)

**Comment by m4heshd** [comment] 2020-01-31 22:33
Closing this since it's a duplicate of #77 and has been fixed in the latest release.

**Closed as completed by m4heshd** 2020-01-31 22:33 UTC
Labels: Duplicate
